#!/usr/bin/env python3
"""
Generate _data/recent.yml for the "Recent" block on the landing page.

Reads _pages/publications.md — the canonical, hand-curated list — and writes
the newest N peer-reviewed journal articles to _data/recent.yml, which
_pages/about.md renders. Nothing is duplicated by hand: edit publications.md
as usual, run this, commit.

Usage:
    python3 update_recent.py [N]        # default N = 3
"""

import os
import re
import sys
import html

N = int(sys.argv[1]) if len(sys.argv) > 1 else 3

REPO_ROOT = os.path.dirname(os.path.abspath(__file__))
PUBS_PATH = os.path.join(REPO_ROOT, "_pages", "publications.md")
OUT_PATH = os.path.join(REPO_ROOT, "_data", "recent.yml")

source = open(PUBS_PATH, encoding="utf-8").read()

# only the peer-reviewed journal articles section, which is ordered newest first
start = source.find("## Peer-reviewed Journal Articles")
end = source.find("\n## ", start + 1)
section = source[start:end if end != -1 else len(source)]

entries = re.findall(r'<div class="pub-entry">(.*?)\n</div>', section, re.S)

items = []
for entry in entries[:N]:
    text = re.search(r'<div class="pub-text">(.*?)</div>', entry, re.S)
    if not text:
        continue
    raw = text.group(1)

    # citation text without the leading number and without markup
    citation = re.sub(r'<span class="pub-num">.*?</span>', "", raw)
    citation = re.sub(r"<[^>]+>", "", citation)
    citation = html.unescape(" ".join(citation.split()))

    # journal name sits in <em><strong>...</strong></em>
    venue = re.search(r"<em><strong>(.*?)</strong></em>", raw, re.S)
    venue = html.unescape(re.sub(r"<[^>]+>", "", venue.group(1)).strip()) if venue else ""

    # title: between the year in parentheses and the venue
    title = re.search(r"\(\d{4}[a-z]?\)\.\s*(.*?)\.\s*$", citation.split(venue)[0].strip())
    title = title.group(1).strip() if title else ""

    year = re.search(r"\((\d{4})[a-z]?\)", citation)
    year = year.group(1) if year else ""

    link = re.search(r'href="(https?://(?:doi\.org|osf\.io)[^"]*)"', entry)
    link = link.group(1) if link else ""

    items.append({"title": title, "venue": venue, "year": year, "url": link})


def q(value):
    return '"' + str(value).replace('"', '\\"') + '"'


with open(OUT_PATH, "w", encoding="utf-8") as out:
    out.write("# Generated by update_recent.py — do not edit by hand.\n")
    out.write("# Source: _pages/publications.md\n")
    for item in items:
        out.write("- title: %s\n" % q(item["title"]))
        out.write("  venue: %s\n" % q(item["venue"]))
        out.write("  year: %s\n" % q(item["year"]))
        out.write("  url: %s\n" % q(item["url"]))

print("Wrote %d entries to %s" % (len(items), OUT_PATH))
for item in items:
    print("  %s (%s) — %s" % (item["title"][:60], item["year"], item["venue"]))
